---
title: "acorn_clean_notebook"
output: html_notebook
---
 

```{r}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lmtest)
library(tableone)
library(officer)

```

```{r}
library(readxl)
acorn_data <- read_excel("acorn_data.xlsx")
View(acorn_data)

overview <- acorn_data
```

```{r}
#look at missing data for white count

table(overview$baseline_wbc, useNA = "ifany")

#exclude 110 with missing values for baseline wbc

overview_new <- overview[-(which(overview$baseline_wbc %in% NA)), ]
table(overview_new$baseline_wbc, useNA = "ifany")

#look at distribution of white count for remaining patients
wbc_dist <- ggplot(overview_new, aes(x = baseline_wbc)) +
  geom_histogram()
#still some people with extremely high initial wbc

length(which(overview_new$baseline_wbc > 50)) #15 rows > 50
length(which(overview_new$baseline_wbc > 75)) #5 rows > 75
length(which(overview_new$baseline_wbc > 100)) #only 1 > 100, will remove that value

overview_new <- overview_new %>%
  filter(baseline_wbc < 100)

#remove outlier
wbc_dist_clean <- ggplot(overview_new, aes(x = baseline_wbc)) +
  geom_histogram() 

```


```{r}
#select variables of interest
smart_abx = overview_new%>%rename(id=record_id)%>%
                          mutate(CKD = ifelse(CKD==2,1,CKD))%>%
                          mutate(CKD = ifelse(is.na(CKD),0,CKD))%>%
                        dplyr::select(id, trt_group, inhosp_mortality28, death14_newrrt14, icufreedays28, delc14, comagdelcfreedays14, comagdelc14, persistent_renal_dysfunction28, rrtfreedays28, newrrt28, newrrt14, highest_cr_28, age, sex, race.eth, baseline_sofa, baseline_coma_delirium, incident_aki_with_onstudy_14.factor, CKD, sepsis, received_vancomycin_14, received_assigned_therapy_28, MAKE14, preill_creat_calculate, preill_creat, preill_creat_observed,
                                      baseline_vent, baseline_anyvasopressor, source_of_infection, location, priorhd, days_assigned_therapy_14, baseline_wbc)%>%
  mutate(n=1)%>%
  mutate(race_white = ifelse(race.eth=="White, Non-Hispanic", 1, 0))%>%
  mutate(coma= as.factor(comagdelcfreedays14))

smart_abx$incident_aki_with_onstudy_14.factor <- ordered(smart_abx$incident_aki_with_onstudy_14.factor,
                                                         levels = c("Alive without AKI", "Stage 1 AKI", 
                                     
                                                               "Stage 2 AKI", "Stage 3 AKI", "Died"))

smart_abx$source_of_infection <- as.factor(smart_abx$source_of_infection)


```


```{r}
#look for missing data here
#count missing values in each variable

sapply(smart_abx, function(x) sum(is.na(x)))

#bar graph of missing values
freqDf <- data.frame(table(is.na(smart_abx))) 
  
# barplot for visualization 
barplot(freqDf$Freq , main = "Total Missing values", 
xlab = "Missing Data", ylab = "Frequency",  
        names.arg = c("FALSE","TRUE"), 
col = c("#80dfff","lightgreen")) 
  
# legend for barplot 
legend("topright", 
c("Non-Missing Values","Missing Values"), 
fill = c("#80dfff","lightgreen")) 
```


```{r}
#are missing variables values for wbc related to any predictors?

overview_missing <- overview_new %>%
  mutate(wbc_missing = ifelse(is.na(baseline_wbc), 0, 1))

missing_relationship <- glm(wbc_missing ~ age + sex+  baseline_sofa + baseline_vent + baseline_anyvasopressor + preill_creat + priorhd + source_of_infection + location, data = overview_missing, family = "binomial")
summary(missing_relationship)
```

```{r}
##creating Table 1
#characteristics to capture: age, sex, race, smoking, baseline creatinine, Charlson, baseline qSOFA, infection source

#table 1 with patient level stuff
myVars <- c("trt_group", "vancomycin_day0","received_vancomycin_14", "age",  "bmi",  "baseline_sofa", "daysaccurate_timezero_firstanyantibiotics", "CHARLSON", "sex", "race.eth", "baseline_vent", "prevalent_aki.factor", "sepsis", "source_of_infection", "baseline_anyvasopressor", "inhosp_mortality28", "MAKE14", "comagdelcfreedays14", "baseline_coma_delirium")

catVars <- c("trt_group", "vancomycin_day0","received_vancomycin_14","sex", "race.eth", "baseline_vent", "prevalent_aki.factor", "sepsis", "source_of_infection", "baseline_anyvasopressor", "inhosp_mortality28")

table1 <- CreateTableOne(vars = myVars, overview_new, factorVars = catVars)
table1

table1 <- print(table1, quote = FALSE, noSpaces = TRUE, printToggle = FALSE)
## Save to a CSV file
write.csv(table1, file = "myTable.csv")

#repeat, stratified by treatment group
table1_trt_group <- CreateTableOne(vars = myVars, overview_new, factorVars = catVars, strata = c("trt_group"))
table1_trt_group

```


```{r}
#interaction model
interaction_model <- function(predictor, data) {
modx <- glm(predictor ~ trt_group +  baseline_wbc + baseline_wbc*trt_group + age + sex+  baseline_sofa + baseline_vent + baseline_anyvasopressor + source_of_infection + location + preill_creat + priorhd, data = data, family = "binomial")
}

model_results <- function(result) {
  mod.sumx <- summary(result)
  mod.expx <- cbind(
    OR = exp(coef(result)),
    exp(confint(result)),
    p = mod.sumx$coefficients[, "Pr(>|z|)"]
  )
}

#test with 28-day mortality
mortality_int <- interaction_model(smart_abx$inhosp_mortality28, smart_abx)

#result
mortality_int_result <- model_results(mortality_int)

#no interaction model
no_interaction_model <- function(predictor, data) {
mody <- glm(predictor ~  trt_group + baseline_wbc + age + sex+  baseline_sofa + baseline_vent + baseline_anyvasopressor + source_of_infection + location + preill_creat + priorhd, data = data, family = "binomial")
}

```

```{r}
#effect modification by white count
#28 day mortality
moda <- glm(inhosp_mortality28 ~ trt_group +  baseline_wbc + baseline_wbc*trt_group + age + sex+  baseline_sofa + baseline_vent + baseline_anyvasopressor + source_of_infection + location + preill_creat + priorhd, data = smart_abx, family = "binomial")
  mod.suma <- summary(moda)
  mod.expa <- cbind(
    OR = exp(coef(moda)),
    exp(confint(moda)),
    p = mod.suma$coefficients[, "Pr(>|z|)"]
  )
 
modb <- glm(inhosp_mortality28 ~  trt_group + baseline_wbc + age + sex+  baseline_sofa + baseline_vent + baseline_anyvasopressor + source_of_infection + location + preill_creat + priorhd, data = smart_abx, family = "binomial")
  mod.sumb <- summary(modb)
  mod.expb <- cbind(
    OR = exp(coef(modb)),
    exp(confint(modb)),
    p = mod.sumb$coefficients[, "Pr(>|z|)"]
  )
  
  lrtest(moda, modb)
```


```{r}
#make 14
make14_int <- interaction_model(smart_abx$MAKE14, smart_abx)

make14 <- no_interaction_model(smart_abx$MAKE14, smart_abx)

#interaction results
make14_int_result <- model_results(make14_int)

#no interaction results
make14_results <- model_results(make14)

lrtest(make14_int, make14)
```

```{r}
#incident aki
aki_int = MASS::polr(incident_aki_with_onstudy_14.factor ~ trt_group +  baseline_wbc + baseline_wbc*trt_group + age + sex+  baseline_sofa + baseline_vent + baseline_anyvasopressor + preill_creat + priorhd + source_of_infection + location, data = smart_abx, Hess = TRUE)
aki = MASS::polr(incident_aki_with_onstudy_14.factor ~ trt_group +  baseline_wbc + age + sex+  baseline_sofa + baseline_vent + baseline_anyvasopressor + preill_creat + priorhd + source_of_infection + location, data = smart_abx, Hess = TRUE)

anova(aki_int, aki, test ="Chisq")

#interaction results
aki_int_sum <- summary(aki_int)
  
aki_int_ci <- confint(aki_int)
aki_int_results <- exp(cbind(OR = coef(aki_int), aki_int_ci))

#no interaction results
aki_sum <- summary(aki)

aki_ci <- confint(aki)
aki_results <- exp(cbind(OR = coef(aki), aki_ci))

#detailed interaction results with p values
summary_aki_cont <- summary(aki_int)

# Extract coefficients and standard errors
coefficients <- coef(summary_aki_cont)
z_values <- coefficients[, "Value"] / coefficients[, "Std. Error"]  # Calculate Z-values
p_values <- 2 * pnorm(abs(z_values), lower.tail = FALSE)  # Two-tailed p-values

# Combine results into a data frame
aki_cont_results <- data.frame(
  Coefficient = coefficients[, "Value"],
  `Std. Error` = coefficients[, "Std. Error"],
  `Z-value` = z_values,
  `P-value` = p_values
)
print(aki_cont_results)

# Calculate odds ratios and confidence intervals
conf_intervals <- confint(aki_int)  # Profile likelihood confidence intervals
odds_ratios <- exp(coef(aki_int))  # Exponentiate coefficients
conf_intervals_exp <- exp(conf_intervals)  # Exponentiate confidence intervals

# Combine ORs and CI into a data frame
aki_or_results <- data.frame(
  OR = odds_ratios,
  `2.5% CI` = conf_intervals_exp[, 1],
  `97.5% CI` = conf_intervals_exp[, 2]
)
print(aki_or_results)

```

```{r}
#incidence of coma or delirium
ever_coma_int <- interaction_model(smart_abx$comagdelc14, smart_abx)

ever_coma <- no_interaction_model(smart_abx$comagdelc14, smart_abx)

lrtest(ever_coma_int, ever_coma)

#interaction results
  
coma_int_results <- model_results(ever_coma_int)

#no interaction results
coma_results <- model_results(ever_coma)

```


```{r}
#sensitivity analysis: sepsis or vancomycin only
sepsis_vanc <- smart_abx %>%
  filter(received_vancomycin_14 == 1 & sepsis == "Yes")

s_v_mortality_int <- interaction_model(sepsis_vanc$inhosp_mortality28, sepsis_vanc)

s_v_mortality <- no_interaction_model(sepsis_vanc$inhosp_mortality28, sepsis_vanc)

lrtest(s_v_mortality_int, s_v_mortality)

#mortality results
s_v_mortality_int_results <- model_results(s_v_mortality_int)

s_v_mortality_results <- model_results(s_v_mortality)
  
```
```{r}
#sensitivity: vanc only
vanc <- smart_abx %>%
  filter(received_vancomycin_14 == 1)

v_mortality_int <- interaction_model(vanc$inhosp_mortality28, vanc)

v_mortality <- no_interaction_model(vanc$inhosp_mortality28, vanc)

lrtest(v_mortality_int, v_mortality)

#mortality results
v_mortality_int_results <- model_results(v_mortality_int)

v_mortality_results <- model_results(v_mortality)
```
```{r}
#sensitivity: baseline sepsis
sepsis <- smart_abx %>%
  filter(sepsis == "Yes")

s_mortality_int <- interaction_model(sepsis$inhosp_mortality28, sepsis)

s_mortality <- no_interaction_model(sepsis$inhosp_mortality28, sepsis)

lrtest(s_mortality_int, s_mortality)

#mortality results
s_mortality_int_results <- model_results(s_mortality_int)

s_mortality_results <- model_results(s_mortality)
```
```{r}
#sensitivity: exclude abdominal infection
no_abdominal <- smart_abx %>%
  filter(source_of_infection != "Intra-abdominal")

no_abdominal$source_of_infection <- droplevels(no_abdominal$source_of_infection)

no_abdominal_mortality_int <- interaction_model(no_abdominal$inhosp_mortality28, no_abdominal)

no_abdominal_mortality <- no_interaction_model(no_abdominal$inhosp_mortality28, no_abdominal)

lrtest(no_abdominal_mortality_int, no_abdominal_mortality)

#mortality results
no_abdominal_mortality_int_results <- model_results(no_abdominal_mortality_int)

no_abdominal_mortality_results <- model_results(no_abdominal_mortality)
```
```{r}
#fast way to get results onto table
install.packages("jtools")
require(jtools)
install.packages("flextable")
require(flextable)
install.packages("openxlsx")
require(openxlsx)

coma_combined_results <- export_summs(ever_coma_int, ever_coma, exp = TRUE,
             error_format = "({conf.low}, {conf.high})", to.file = "xlsx", file.name = "test.xlsx")
```

```{r}
#data visualizaiton by quartile
#create quartiles of initial wbc
smart_abx <- smart_abx %>%
  mutate(wbc_quartile = ntile(baseline_wbc, 4))

#make labeled factor for plots
overview_new <- overview_new %>%
  mutate(wbc_quintile = recode_factor(ntile(baseline_wbc, 4), `1` = "<7", `2` = "7-11", `3` = "11-16", `4` = ">16"))

```

```{r}
#table one by quartile
#table 1 with patient level stuff
myVars <- c("trt_group", "vancomycin_day0","received_vancomycin_14", "age",  "bmi",  "baseline_sofa", "daysaccurate_timezero_firstanyantibiotics", "CHARLSON", "sex", "race.eth", "baseline_vent", "prevalent_aki.factor", "sepsis", "source_of_infection", "baseline_anyvasopressor", "inhosp_mortality28", "MAKE14", "comagdelcfreedays14", "baseline_coma_delirium")

catVars <- c("trt_group", "vancomycin_day0","received_vancomycin_14","sex", "race.eth", "baseline_vent", "prevalent_aki.factor", "sepsis", "source_of_infection", "baseline_anyvasopressor", "inhosp_mortality28")

table1 <- CreateTableOne(vars = myVars, overview_new, factorVars = catVars, strata = c("wbc_quartile"))
table1

table1 <- print(table1, quote = FALSE, noSpaces = TRUE, printToggle = FALSE)
## Save to a CSV file
write.csv(table1, file = "myTable.csv")
```

```{r}
#look at baseline characteristics only in highest quartile

overview_q4 <- subset(overview_new, wbc_quartile == 4)


#table 1 with patient level stuff
Vars <- c("trt_group", "vancomycin_day0","received_vancomycin_14", "age",  "bmi",  "baseline_sofa", "daysaccurate_timezero_firstanyantibiotics", "CHARLSON", "sex", "race.eth", "baseline_vent", "prevalent_aki.factor", "sepsis", "source_of_infection", "baseline_anyvasopressor", "inhosp_mortality28", "MAKE14", "comagdelcfreedays14", "baseline_coma_delirium")

catVars <- c("vancomycin_day0","received_vancomycin_14","sex", "race.eth", "baseline_vent", "prevalent_aki.factor", "sepsis", "source_of_infection", "baseline_anyvasopressor")

q4_table1 <- CreateTableOne(vars = Vars, overview_q4, factorVars = catVars, strata = c("trt_group"))
q4_table1

q4_table1 <- print(q4_table1, quote = FALSE, noSpaces = TRUE, printToggle = FALSE)
## Save to a CSV file
write.csv(q4_table1, file = "q4Table.csv")

#repeat for each quartile
#q1
overview_q1 <- subset(overview_new, wbc_quintile == "<7")
q1_table <- CreateTableOne(vars = q4Vars, overview_q1, factorVars = q4catVars, strata = c("trt_group"))

#q2
overview_q2 <- subset(overview_new, wbc_quintile == "7-11")
q2_table <- CreateTableOne(vars = q4Vars, overview_q2, factorVars = q4catVars, strata = c("trt_group"))

q2_table <- print(q2_table, quote = FALSE, noSpaces = TRUE, printToggle = FALSE)
## Save to a CSV file
write.csv(q2_table, file = "q2_Table.csv")

#q3
overview_q3 <- subset(overview_new, wbc_quintile == "11-16")
q3_table <- CreateTableOne(vars = q4Vars, overview_q3, factorVars = q4catVars, strata = c("trt_group"))

q3_table <- print(q3_table, quote = FALSE, noSpaces = TRUE, printToggle = FALSE)
## Save to a CSV file
write.csv(q3_table, file = "q3_Table.csv")
```

```{r}
#28 day mortality by quartile
moda <- glm(inhosp_mortality28 ~ trt_group +  wbc_quartile + wbc_quartile*trt_group + age + sex+  baseline_sofa + baseline_vent + baseline_anyvasopressor + factor(source_of_infection) + location + preill_creat_calculate + priorhd, data = smart_abx, family = "binomial")
  mod.suma <- summary(moda)
  mod.expa <- cbind(
    OR = exp(coef(moda)),
    exp(confint(moda)),
    p = mod.suma$coefficients[, "Pr(>|z|)"]
  )
 
  modb <- glm(inhosp_mortality28 ~  trt_group + factor(wbc_quartile) + age + sex+  baseline_sofa + baseline_vent + baseline_anyvasopressor + factor(source_of_infection) + location + preill_creat_calculate + priorhd, data = smart_abx, family = "binomial")
  mod.sumb <- summary(modb)
  mod.expb <- cbind(
    OR = exp(coef(modb)),
    exp(confint(modb)),
    p = mod.sumb$coefficients[, "Pr(>|z|)"]
  )
  
  lrtest(moda, modb)
  
```

```{r}
#make14 by quartile
make_quart_int <- glm(MAKE14 ~ trt_group +  wbc_quartile + wbc_quartile*trt_group + age + sex+  baseline_sofa + baseline_vent + baseline_anyvasopressor + factor(source_of_infection) + location + preill_creat + priorhd, data = smart_abx, family = "binomial")
  mod.sum.make.int <- summary(make_quart_int)
  make_quart_int_results <- cbind(
    OR = exp(coef(make_quart_int)),
    exp(confint(make_quart_int)),
    p = mod.sum.make.int$coefficients[, "Pr(>|z|)"]
  )
 
  make_quart <- glm(MAKE14 ~  trt_group + wbc_quartile + age + sex+  baseline_sofa + baseline_vent + baseline_anyvasopressor + factor(source_of_infection) + location + preill_creat + priorhd, data = smart_abx, family = "binomial")
  mod.sum.make <- summary(make_quart)
  make_quart_results <- cbind(
    OR = exp(coef(make_quart)),
    exp(confint(make_quart)),
    p = mod.sum.make$coefficients[, "Pr(>|z|)"]
  )
  
  lrtest(make_quart_int, make_quart)
```

```{r}

smart_abx$wbc_quartile <- as.factor(smart_abx$wbc_quartile)

#incident aki
aki.a <- MASS::polr(incident_aki_with_onstudy_14.factor ~ trt_group + wbc_quartile + wbc_quartile*trt_group + age + sex +  baseline_sofa + baseline_vent + baseline_anyvasopressor + preill_creat + factor(source_of_infection) + location, data = smart_abx, Hess = TRUE)

aki.b <- MASS::polr(incident_aki_with_onstudy_14.factor ~ trt_group + factor(wbc_quartile) + age + sex +  baseline_sofa + baseline_vent + baseline_anyvasopressor + preill_creat + factor(source_of_infection) + location, data = smart_abx, Hess = TRUE)

summary_aki <- summary(aki.a)

# Extract coefficients and standard errors
coefficients <- coef(summary_aki)
z_values <- coefficients[, "Value"] / coefficients[, "Std. Error"]  # Calculate Z-values
p_values <- 2 * pnorm(abs(z_values), lower.tail = FALSE)  # Two-tailed p-values

# Combine results into a data frame
results <- data.frame(
  Coefficient = coefficients[, "Value"],
  `Std. Error` = coefficients[, "Std. Error"],
  `Z-value` = z_values,
  `P-value` = p_values
)
print(results)

# Calculate odds ratios and confidence intervals
conf_intervals <- confint(aki.a)  # Profile likelihood confidence intervals
odds_ratios <- exp(coef(aki.a))  # Exponentiate coefficients
conf_intervals_exp <- exp(conf_intervals)  # Exponentiate confidence intervals

# Combine ORs and CI into a data frame
or_results <- data.frame(
  OR = odds_ratios,
  `2.5% CI` = conf_intervals_exp[, 1],
  `97.5% CI` = conf_intervals_exp[, 2]
)
print(or_results)

```

```{r}
#coma or delirium incidence
ever_coma_int_quart = glm(comagdelc14 ~ trt_group +  wbc_quartile + wbc_quartile*trt_group + age + sex+  baseline_sofa  + baseline_anyvasopressor + preill_creat + priorhd + factor(source_of_infection) + location, data = smart_abx, family = "binomial")
ever_coma_quart = glm(comagdelc14 ~ trt_group +  wbc_quartile + age + sex+  baseline_sofa  + baseline_anyvasopressor + preill_creat + priorhd + factor(source_of_infection) + location, data = smart_abx, family = "binomial")

lrtest(ever_coma_int_quart, ever_coma_quart)

ever_coma_int_quart_sum <- summary(ever_coma_int_quart)

ever_coma_quart_int_results <- cbind(
    OR = exp(coef(ever_coma_int_quart)),
    exp(confint(ever_coma_int_quart)),
    p = ever_coma_int_quart_sum$coefficients[, "Pr(>|z|)"]
  )

ever_coma_quart_sum <- summary(ever_coma_quart)
ever_coma_quart_results <- cbind(
    OR = exp(coef(ever_coma_quart)),
    exp(confint(ever_coma_quart)),
    p = ever_coma_quart_sum$coefficients[, "Pr(>|z|)"]
  )
```
```{r}
#odds of outcome in each quartile
#mortality
stratified_model <- function(outcome, data) {
    modx <- glm(outcome ~ trt_group + age + sex+  baseline_sofa + baseline_vent + baseline_anyvasopressor + factor(source_of_infection) + location + preill_creat + priorhd, data = data, family = "binomial")
  mod.sumx <- summary(modx)
  OR.quartile <- cbind(
    OR = exp(coef(modx)),
    exp(confint(modx)),
    p = mod.sumx$coefficients[, "Pr(>|z|)"]
  )
  return(OR.quartile)
}

#mortality in each quartile
q1_OR <- stratified_model(q1$inhosp_mortality28, q1)
q2_OR <- stratified_model(q2$inhosp_mortality28, q2)
q3_OR <- stratified_model(q3$inhosp_mortality28, q3)
q4_OR <- stratified_model(q4$inhosp_mortality28, q4)

#install package to make forest plot
install.packages("forestploter")
library(forestploter)

quartile_OR_data <- tibble('WBC Quartile' = c("<7", "7-11", "11-16", ">16"), 
                           OR = c(1.68, 1.49, 0.92, 0.51), 
                           LL = c(0.84, 0.64, 0.43, 0.29), 
                           UL = c(3.50, 3.52, 1.94, 0.90))

# Add a blank column for the forest plot to display CI.
# Adjust the column width with space, and increase the number of spaces below 
# to have a larger area to draw the CI. 
quartile_OR_data$` ` <- paste(rep(" ", 35), collapse = " ")


# Create a confidence interval column to display
quartile_OR_data$`OR (95% CI)` <- sprintf("%.2f (%.2f to %.2f)",
                                     quartile_OR_data$OR, quartile_OR_data$LL, quartile_OR_data$UL)

tm <- forest_theme(core=list(fg_params=list(hjust=01, x=0.9)), rowhead=list(fg_params=list(hjust=0.5, x=0.5)), padding = unit(c(50, 50), "mm"))

OR_forest <- forest(quartile_OR_data[, c(1, 5:6)],
            est = quartile_OR_data$OR,
            lower = quartile_OR_data$LL, 
            upper = quartile_OR_data$UL,
            ci_column = 2,
            ref_line = 1,
            xlim = c(0, 2),
            ticks_at = c(0.5, 1, 1.5, 2),
            title = "28-Day Mortality", 
            theme = tm)
OR_forest
```


```{r}
#make14
#make14
q1_make_OR <- stratified_model(q1$MAKE14, q1)
q2_make_OR <- stratified_model(q2$MAKE14, q2)
q3_make_OR <- stratified_model(q3$MAKE14, q3)
q4_make_OR <- stratified_model(q4$MAKE14, q4)

quartile_OR_data <- tibble('WBC Quartile' = c("<7", "7-11", "11-16", ">16"), 
                           OR = c(1.38, 0.84, 0.89, 0.57), 
                           LL = c(0.71, 0.39, 0.44, 0.33), 
                           UL = c(2.76, 1.77, 1.81, 0.96))

# Add a blank column for the forest plot to display CI.
# Adjust the column width with space, and increase the number of spaces below 
# to have a larger area to draw the CI. 
quartile_OR_data$` ` <- paste(rep(" ", 35), collapse = " ")


# Create a confidence interval column to display
quartile_OR_data$`OR (95% CI)` <- sprintf("%.2f (%.2f to %.2f)",
                                     quartile_OR_data$OR, quartile_OR_data$LL, quartile_OR_data$UL)

tm <- forest_theme(core=list(fg_params=list(hjust=01, x=0.9)), rowhead=list(fg_params=list(hjust=0.5, x=0.5)), padding = unit(c(50, 50), "mm"))

make_OR_forest <- forest(quartile_OR_data[, c(1, 5:6)],
            est = quartile_OR_data$OR,
            lower = quartile_OR_data$LL, 
            upper = quartile_OR_data$UL,
            ci_column = 2,
            ref_line = 1,
            xlim = c(0, 2),
            ticks_at = c(0.5, 1, 1.5, 2),
            title = "MAKE14", 
            theme = tm)
make_OR_forest
```


```{r}
#incident aki
stratified_aki_function <- function(data) {
  model <- MASS::polr(incident_aki_with_onstudy_14.factor ~ trt_group + age + sex+  baseline_sofa + baseline_vent + baseline_anyvasopressor + preill_creat + priorhd + factor(source_of_infection) + location, data = data, Hess = TRUE)

#results table
ci <- confint.default(model)
results <- exp(cbind(OR = coef(model), ci))

return(results)
}


q1_aki_or <- stratified_aki_function(q1)
q2_aki_or <- stratified_aki_function(q2)
q3_aki_or <- stratified_aki_function(q3)
q4_aki_or <- stratified_aki_function(q4)

quartile_OR_data <- tibble('WBC Quartile' = c("<7", "7-11", "11-16", ">16"), 
                           OR = c(1.16, 1.27, 1.10, 0.90), 
                           LL = c(0.78, 0.82, 0.72, 0.64), 
                           UL = c(1.73, 1.96, 1.70, 1.28))

# Add a blank column for the forest plot to display CI.
# Adjust the column width with space, and increase the number of spaces below 
# to have a larger area to draw the CI. 
quartile_OR_data$` ` <- paste(rep(" ", 35), collapse = " ")


# Create a confidence interval column to display
quartile_OR_data$`OR (95% CI)` <- sprintf("%.2f (%.2f to %.2f)",
                                     quartile_OR_data$OR, quartile_OR_data$LL, quartile_OR_data$UL)

tm <- forest_theme(core=list(fg_params=list(hjust=01, x=0.9)), rowhead=list(fg_params=list(hjust=0.5, x=0.5)), padding = unit(c(50, 50), "mm"))

aki_OR_forest <- forest(quartile_OR_data[, c(1, 5:6)],
            est = quartile_OR_data$OR,
            lower = quartile_OR_data$LL, 
            upper = quartile_OR_data$UL,
            ci_column = 2,
            ref_line = 1,
            xlim = c(0, 2),
            ticks_at = c(0.5, 1, 1.5, 2),
            title = "Incident AKI", 
            theme = tm)
aki_OR_forest


```

```{r}
#coma delirium
#ever coma by quartile to add to figure
#ever coma in each quartile
q1_coma_OR <- stratified_model(q1$comagdelc14, q1)
q2_coma_OR <- stratified_model(q2$comagdelc14, q2)
q3_coma_OR <- stratified_model(q3$comagdelc14, q3)
q4_coma_OR <- stratified_model(q4$comagdelc14, q4)

#aki forest
quartile_OR_data <- tibble('WBC Quartile' = c("<7", "7-11", "11-16", ">16"), 
                           OR = c(0.82, 0.79, 0.58, 1.12), 
                           LL = c(0.44, 0.39, 0.32, 0.67), 
                           UL = c(1.50, 1.56, 1.02, 1.88))

# Add a blank column for the forest plot to display CI.
# Adjust the column width with space, and increase the number of spaces below 
# to have a larger area to draw the CI. 
quartile_OR_data$` ` <- paste(rep(" ", 35), collapse = " ")


# Create a confidence interval column to display
quartile_OR_data$`OR (95% CI)` <- sprintf("%.2f (%.2f to %.2f)",
                                     quartile_OR_data$OR, quartile_OR_data$LL, quartile_OR_data$UL)


tm <- forest_theme(core=list(fg_params=list(hjust=01, x=0.9)), rowhead=list(fg_params=list(hjust=0.5, x=0.5)), padding = unit(c(50, 50), "mm"))

coma_OR_forest <- forest(quartile_OR_data[, c(1, 5:6)],
            est = quartile_OR_data$OR,
            lower = quartile_OR_data$LL, 
            upper = quartile_OR_data$UL,
            ci_column = 2,
            ref_line = 1,
            arrow_lab = c("Favors piperacillin/tazobactam", "Favors Cefepime"),
            xlim = c(0, 2),
            ticks_at = c(0.5, 1, 1.5, 2),
            title = "Coma or Delirium", 
            theme = tm)
coma_OR_forest
```
```{r}
#powerful way to get data by quartile that involves no typing!
#could also use lapply instead of map or vice versa

library(broom)
library(purrr)
library(forcats)

quartile_OR_data <- smart_abx %>%
  group_by(wbc_quartile) %>%
  nest() %>%
  mutate(
    fit = map(data, function(df) glm(inhosp_mortality28 ~ trt_group + age + sex+  baseline_sofa + baseline_vent + baseline_anyvasopressor + source_of_infection + preill_creat + priorhd, data = df, family = "binomial")),
    output = map(fit, tidy),
    ci = map(fit, confint)) %>%
  unnest(c(output, ci)) %>%
  filter(term == "trt_groupzosyn") %>% 
  mutate(
    OR = exp(estimate),
    LL = exp(ci[,1]),
    UL = exp(ci[2])
  ) %>% 
  select(wbc_quartile, OR, LL, UL)  %>%
  arrange(wbc_quartile) %>%
  mutate('WBC Quartile' = factor(wbc_quartile, levels = c(1, 2, 3, 4), labels = c("<7", "7-11", "11-16", ">16"))) %>%
  select('WBC Quartile', OR, LL, UL)
```
```{r}
#calculate marginal effects of model to estimate effect size

install.packages("marginaleffects")
library(marginaleffects)

# Plot conditional adjusted predictions
predictions_plot <- plot_predictions(moda, condition = list("baseline_wbc", "trt_group"))

#plot conditional marginal effects--how the derivative of hospital mortality with respect to treatment group varies as a function of baseline wbc 
plot_slopes(moda, variables = "trt_group", condition = list("baseline_wbc"))

#obtain average slopes (marginal effects over the whole model)

avg_slopes(moda, variables = "baseline_wbc", by = "trt_group")

#average comparisons
avg_comparisons(moda, variables = "baseline_wbc", by = "trt_group")
```
```{r}
#trying some things by quartile
mod_quart <- glm(inhosp_mortality28 ~ trt_group +  wbc_quartile + age + sex+  baseline_sofa + baseline_vent + baseline_anyvasopressor + factor(source_of_infection) + location + preill_creat_calculate + priorhd, data = smart_abx, family = "binomial")

#estimate the partial derivative of in hospital mortality with respect to wbc quartile by treatment group
slopes(
  mod_quart,
  variables = "wbc_quartile",
  newdata = datagrid("trt_group"))

#make a tree
install.packages("partykit")
library(partykit)

tree <- ctree(
    inhosp_mortality28 ~ wbc_quartile + as.factor(trt_group),
    data = smart_abx,
    control = ctree_control(maxdepth = 2)
)

plot(tree)

dat <- transform(smart_abx, nodeid = predict(tree, type = "node"))
comparisons(mod_quart,
    newdata = dat,
    by = "nodeid")
```

```{r}
#wbc quartile characteristics
smart_abx %>%
  group_by(wbc_quartile) %>%
  summarize(
    mean = mean(baseline_wbc),
    range = range(baseline_wbc))
  
```

